title: Hey I'm Hodon 
author: Hodon Ali
email: Hodonabdullahi@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: Hodonali2
github_username:  Hodonali

show_excerpts: true # set to false to remove excerpts on the homepage
